pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'Heartcooking-SPA'
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: 'Heartcooking-SPA'
    verbose: false
    customCommand: 'run build -- --prod'

- task: Npm@1
  displayName: 'npm test-ci'
  inputs:
    command: custom
    workingDir: 'Heartcooking-SPA'
    verbose: false
    customCommand: 'run test-ci'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TESTS-*.xml'
  inputs:
    testResultsFiles: '**/TESTS-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/Heartcooking-SPA/junit'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from Heartcooking-SPA/coverage/Heartcooking-SPA/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'Heartcooking-SPA/coverage/Heartcooking-SPA/cobertura-coverage.xml'
    failIfCoverageEmpty: true

