trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Heartcooking.API/*
    - Heartcooking.API.tests/*

pool:
  name: Azure Pipelines
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: Heartcooking.API/Heartcooking.API.csproj

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Heartcooking.API/Heartcooking.API.csproj
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'Heartcooking.API.tests\Heartcooking.API.UnitTests\Heartcooking.API.UnitTests.csproj'
    arguments: '--configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]*"'

- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: ReportGenerator
  inputs:
    reports: '**/coverage.cobertura.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from **/coverage.cobertura.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/coverage.cobertura.xml'
    reportDirectory: CoverageReport

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: Heartcooking.API/Heartcooking.API.csproj
    arguments: '--configuration Release'

